apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/gpu-zonal-redundancy-disabled: 'true'
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      containerConcurrency: 10
      timeoutSeconds: 300
      nodeSelector:
        run.googleapis.com/accelerator: nvidia-l4
      containers:
        - image: ${CONTAINER_IMAGE}
          ports:
            - name: http1
              containerPort: 8000
          resources:
            limits:
              cpu: '8'
              memory: 32Gi
              nvidia.com/gpu: '1'
          # Startup probe: wait for model to fully load (up to 30 minutes)
          # Uses /v1/models which only returns 200 when model is ready
          startupProbe:
            httpGet:
              path: /v1/models
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 60
          # Liveness probe: basic health check once running
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          env:
            # Run:ai Model Streamer S3-compatible config for GCS
            # Both AWS_ENDPOINT_URL and RUNAI_STREAMER_S3_ENDPOINT needed for full compatibility
            - name: RUNAI_STREAMER_S3_USE_VIRTUAL_ADDRESSING
              value: '0'
            - name: AWS_EC2_METADATA_DISABLED
              value: 'true'
            - name: AWS_ENDPOINT_URL
              value: 'https://storage.googleapis.com'
            - name: RUNAI_STREAMER_S3_ENDPOINT
              value: 'https://storage.googleapis.com'
            # AWS SDK requires a region even for S3-compatible endpoints
            - name: AWS_DEFAULT_REGION
              value: 'auto'
            # Debug logging (remove after successful deployment)
            - name: RUNAI_STREAMER_S3_TRACE
              value: '1'
            - name: RUNAI_STREAMER_LOG_LEVEL
              value: 'DEBUG'
            # HMAC credentials for GCS S3-compatible access
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: HMAC_ACCESS_KEY
                  key: latest
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: HMAC_SECRET_KEY
                  key: latest
            # Model configuration
            - name: MODEL_ID
              value: ${MODEL_ID}
            - name: MODEL_WEIGHTS_BUCKET
              value: ${MODEL_WEIGHTS_BUCKET}
